language: cpp

dist: bionic

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y cdbs fakeroot debhelper-compat libsdl1.2-dev libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-ttf2.0-dev libluajit-5.1-dev liblua5.1-0-dev lua-socket-dev lua-ljsyscall lua-lgi-dev lua-socket-dev lua-filesystem-dev lua-cqueues-dev lua-bitop-dev lua-cjson-dev libgirepository1.0-dev 

script: 
- dpkg-buildpackage -us -uc -rfakeroot

deploy:
  provider: releases
  file_glob: true
  overwrite: true
  draft: true
  file: 
    - "../jivelite*.deb"
    - "../jivelite*.tar.gz"
  skip_cleanup: true
  on:
    repo: andreas-volz/jivelite
